### ISSUE TITLE
Create a github app

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#1]
**Is your feature request related to a problem? Please describe.**
Our application needs authentication and authorization through github, to do this, we chose to use the github app approach, however, it has not yet been created.

**Describe the solution you'd like**
I would like to see our github app created

**Describe alternatives you've considered**
For create the github app, it's enough follow [this instructions](https://developer.github.com/apps/building-github-apps/creating-a-github-app/)

**Additional context**
.

**Comment by jadsonluan** [comment]
https://github.com/apps/panelinha-de-es
