### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by LukeHxH** [panelinhadees/server#11]
**Is your feature request related to a problem? Please describe.**
We need to have a good `README.md` to make explicit what has to be done to run the server.

**Describe the solution you'd like**
Self-explainatory.

**Describe alternatives you've considered**
I don't think a meeting is needed, because we can get things done by discussing in this issue about important points that have to be in the file.

Essential points:

- [x] A concise description of the server.
- [ ] Small introduction for the problem we are trying to solve.
- [x] Describe how to setup the development environment (install node dependencies, docker...).
- [ ] Describe what is needed to run the server (things like environment variables).
- [x] Links for all documentation required (our API, Github API v4 and GraphQL documentations).
- [ ] Examples.

We can have links for:
- [ ] Contributing.
- [ ] Changelog.
- [ ] Issues.
- [ ] Code of conduct (if any).
- [ ] License (if any).

**Comment by LukeHxH** [comment]
Essential points:

- A concise description of the server.
- Describe how to setup the development environment (install node dependencies, docker...).
- Describe what is needed to run the server (things like environment variables).

**Comment by jadsonluan** [comment]
I will be doing this today.

**Comment by LukeHxH** [comment]
@jadsonluan I can help you with that, I'll talk to you via Slack.
