### ISSUE TITLE
Create config.js file

### ISSUE THREAD

**Issue by jadsonluan** [panelinhadees/server#12]
**Is your feature request related to a problem? Please describe.**
We need a dedicated configuration file to gather all the information the server needs about the environment.

**Describe the solution you'd like**
A file with information about client/server host, github app and auth.

**Describe alternatives you've considered**
For the beginning, we can use a config.js file that imports sensitive information from .env files as, for example, github app client_id, client_secret, callback urls, server host, etc.

**Additional context**
[config.js](https://github.com/calluswhatyouwant/musicritic/blob/master/server/config.js)

**Related**
#1 , #2

**Comment by LukeHxH** [comment]
Can this feature be implemented with Docker configuration, as #13? Or maybe we really need to implement `config.js` outside Docker?

**Comment by jadsonluan** [comment]
I think we can do this as docker configuration. If after docker being configured we still need a config.js file we can create one.

**Comment by fanny** [comment]
Our docker config will be flexibe enable use docker or not, because this, config file will be necessary. I will be implement this task too
