### ISSUE TITLE
Create .env.example file

### ISSUE THREAD

**Issue by jadsonluan** [panelinhadees/server#13]
**Is your feature request related to a problem? Please describe.**
We need a dedicated file for gather all sensitive and environment information, but since we can't show the data inside, I would like an example file to guide the user (admin) through the initial configuration needed.

**Describe the solution you'd like**
A .env file with:
- [x] Github OAuth client_id (just w/ example, doesn't showing the real data)
- [x] Github OAuth client_secret (just w/ example, doesn't showing the real data)
- [x] Server base url 
- [x] Server base port
- [x] Client base url
- [x] Client base port

The information related to host (client/server) for while we need just about development environment.

**Describe alternatives you've considered**
In order to not show the information, a placeholder data can be use like this:
- **.env.example**
`GITHUB_OAUTH_CLIENT_ID=your-github-oauth-client-id`

**Additional context**
This [.env.example](https://github.com/calluswhatyouwant/musicritic/blob/master/.env.example) file

**Comment by fanny** [comment]
We can work together to fix this, because in docker config, it's good define env variables
