### ISSUE TITLE
Implement the auth route

### ISSUE THREAD

**Issue by jadsonluan** [panelinhadees/server#14]
**Is your feature request related to a problem? Please describe.**
We need a route to authenticate the user and retrieve a session token.

**Describe the solution you'd like**
A route that I can perform a GET *serverHost*/login and receive a token at *clientHost*/auth/**:token**

**Describe alternatives you've considered**
I implemented an approach based on the one in 'Additional context' section. My approach uses GitHub but it needs more enhancement. The approach: [social-login-github](https://github.com/jadsonluan/social-login-github)

**Additional context**
[Similiar route](https://github.com/calluswhatyouwant/musicritic/blob/master/server/spotify/spotifyAuthController.js)

**Related**
#12

**Comment by fanny** [comment]
Great, i really think that this is valid.
