### ISSUE TITLE
Create project base

### ISSUE THREAD

**Issue by jadsonluan** [panelinhadees/server#15]
**Is your feature request related to a problem? Please describe.**
We need a base for start coding into.

**Describe the solution you'd like**
A boilerplate for start coding into, including npm configs (package.json) and others like babel or folders (src, public, etc).

**Describe alternatives you've considered**
Create a minimal node babel server.

**Additional context**
https://www.robinwieruch.de/minimal-node-js-babel-setup/

**Comment by fanny** [comment]
Great!
