### ISSUE TITLE
Define github app infos

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#2]
**Is your feature request related to a problem? Please describe.**
We need create a github app as describe(#1), but we have not yet defined:

- [x] pemissions for the user
- [x] callback url
- [x] name of app

**Describe the solution you'd like**
I would like have a discussion to define this.

**Describe alternatives you've considered**
We could do the discussion in this issue, because then we can have all this saved, in slack we risk losing

**Additional context**
.

**Comment by jadsonluan** [comment]
I suggest we use a random name from the brainstorm pool and later we can change to the official.

**Comment by fanny** [comment]
I agree with  your opinion about github app name, and for me, the callback url is just '/callback',this is a pattern

**Comment by fanny** [comment]
About github app permission, i think that the 'MetaData' permission is enough, but we can request 'repository administration' too, for get information about teams.

**Comment by jadsonluan** [comment]
Callback url i will use /auth/callback just so we can have a dedicated route (/auth) for authentication. 
Name for while i will use Alvarium (beehive in latim) and the permissions for the beginning will be just MetaData as you describe.
