### ISSUE TITLE
Define github auth flow

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#3]
**Is your feature request related to a problem? Please describe.**
When we authenticate a user, we need the client to send us some information so that we can validate and then return the data, but we have not yet defined how this communication will take place.

**Describe the solution you'd like**
I would like have a discussion to define this.

**Describe alternatives you've considered**
We could do the discussion in this issue, because then we can have all this saved, in slack we risk losing

**Additional context**
[Identifying and authorizing users for github apps](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/)

**Comment by jadsonluan** [comment]
What kind of information from client do we need and why?

**Comment by fanny** [comment]
Hmmm, I do not think it's necessary the client send some information following the link, do you can improve this description?

**Comment by jadsonluan** [comment]
I'm trying to rewrite the description but i can't describe precisely without passing through the solution.

**Comment by fanny** [comment]
Okay, sounds good. You could start searching informations about approaches, and referencing here

**Comment by jadsonluan** [comment]
What i think this [link](https://github.com/calluswhatyouwant/musicritic/blob/master/server/spotify/spotifyAuthController.js) would be helpful. I suggest we try an similiar approach to this.

**Comment by jadsonluan** [comment]
I implemented a solution we can use. [Server repository](https://github.com/jadsonluan/social-login-github) and [Client repository](https://github.com/jadsonluan/eu-aqui-github)

**Comment by fanny** [comment]
I think that this is a good approach to start, and how do we already make a sample, it will be simpler to implement.

**Comment by fanny** [comment]
Du can create derivate tasks to implement the approach?

**Comment by jadsonluan** [comment]
Yes.
