### ISSUE TITLE
Login and get simple organization data

### ISSUE THREAD

**Issue by thayannevls** [panelinhadees/server#42]
**Is your feature request related to a problem? Please describe.**
On our client app it's expected that the user will login using github and after that will see some information about user's organization.

**Describe the solution you'd like**
An endpoint to request the token of login and return me some simple data about the organization, I suggest:

| field   |  type |
:----: | :-----:
name | `string`
avatarUrl | `string`
url | `string`
websiteUrl | `string`

**Describe alternatives you've considered**
Example of query:

```graphql
query { 
  organization(login: "OpenDevUFCG") {
    name
    avatarUrl
    url
    websiteUrl
  }
}
```

**Comment by LukeHxH** [comment]
This is already done, Fanny will approve my PR with the schema that returns data from organization.

But don't close this issue yet, because I'll add data for `avatarUrl` and `websiteUrl`, and then I'll close via a new PR with these data added.

**Comment by fanny** [comment]
> An endpoint to request the token of login and return me some simple data about the organization, I suggest

Instead of this, i think that is : "An endpoint to request the token of login and a schema that allows me make a query to get org info basic data"

**Comment by thayannevls** [comment]
What do you mean @fanny ? What is this schema? Some fields to put in other queries?

**Comment by fanny** [comment]
In graphql, the thinks does not work with endpoint, this would be pass an wrong idea, works with `schemas` in back and `queries` in front

**Comment by thayannevls** [comment]
I know, it's an unique endpoint. What I mean: When I request for login in form of query, I want a response with the token or a data.

If it's the token, I will make a request in another query, right?

**Comment by fanny** [comment]
the token is passed in a callback return url for front

**Comment by fanny** [comment]
i will explain this, here, one second

**Comment by thayannevls** [comment]
Ok! After it's ready, please show me the schema and the fields required in some simple way.

**Comment by fanny** [comment]
1. Clone the repo
2. `npm install`
3. Creates the [.env](https://github.com/panelinhadees/server/blob/master/.env.example)
4. `npm start`
5. Put in client a tag `<a>` to `http://localhost:5000/auth/login`
6. In case of user click in `<a>`, he will be redirect for the GitHub for login, if he not be logged
7. It will be redirected to accept the permissions, if case of sucess, he will be  será levado para o path especificado no .env
8. Se a autenticação for sucesso, será levado pra <client-host>/<path-sucess-do-env>/:token senão pro <client-host>/<path-error-do-env>

**Comment by fanny** [comment]
**Please, note that the token come in the url**
