### ISSUE TITLE
Add pr count information to repo type

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#63]
**Is your feature request related to a problem? Please describe.**
is necessary to include the total of pr field in repo type definition, because our client needs that.

**Describe the solution you'd like**
Add a new field in repo object, in that possible get total of pr information.

**Comment by jadsonluan** [comment]
This information should not be in org type, @fanny ?

**Comment by LukeHxH** [comment]
@jadsonluan I think that #70 refers to organization type, and Fanny may have mistyped it there.

**Comment by fanny** [comment]
@jadsonluan @LukeHxH we will have this information for both the type of repository and the type of organization. So this is correct.

**Comment by LukeHxH** [comment]
@fanny But this issue and #70 have the same title, shouldn't it be "org" in issue #70?

**Comment by fanny** [comment]
Yes, fixed :smiley:

**Comment by fanny** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Contributing
https://docs.firefox-dev.tools/
