### ISSUE TITLE
Define base structure of apollo-server

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#7]
**Is your feature request related to a problem? Please describe.**
How do we use the apollo-server tools, it's necessary to configure the initial file structure 

**Describe the solution you'd like**
I would like to see a basic file structure, that initiates the graphql server

**Describe alternatives you've considered**
In this first moment, we could follow the apollo-server "hello world" tutorial

**Additional context**
[Getting started](https://www.apollographql.com/docs/apollo-server/getting-started)

**Comment by fanny** [comment]
as we define the objects and relationships, the schema, in general mode. We should expand and padronize this structure, something like:

[graphql-module-feature](https://medium.com/the-guild/graphql-modules-feature-based-graphql-modules-at-scale-2d7b2b0da6da)
[apollo-server-chat discusion](https://spectrum.chat/graphql/general/recommendations-for-scale-able-graphql-folder-structure-nodejs~c3936202-f2df-47cc-af96-1d829d34f1d3)

**Comment by jadsonluan** [comment]
I will follow [this](https://www.robinwieruch.de/graphql-apollo-server-tutorial/) since neither the **getting started** nor the apollo server docs explain about routing without a middleware (like express).

**Comment by jadsonluan** [comment]
This issue should be closed by #22 but I closed by mistake the #10 . So, i will close this one and open the #10
